### ISSUE TITLE
Add CLI-installer part 

### ISSUE THREAD

**Issue by sigdestad** [enonic/site-developer#128]
Create a part that can be placed into a black layout, and look as follows: (NB! Dark grey color is the same as used by layout backgrounds). So basically, the top should be transparent, and the panels dark grey.

![Screenshot 2019-03-18 at 13 48 59](https://user-images.githubusercontent.com/482228/54531024-9d97e900-4984-11e9-9cb7-c4b6dac3a23e.png)

Make the "tabs" configurable through an itemSet with the following options:
1. Title
2. SVG
3. Htmlarea (for all text on right side of separator)

Fetch the version info details automatically from enonic repo: NB! Use client side javascript, so this does not delay rendering if page or break it when repo is down.

Reuse functionality from enonic downloads page where possible.

**Comment by hjelmevold** [comment]
Deployed to production in a mostly-completed state. TODO: Look up latest version using client-side JS

**Comment by sigdestad** [comment]
Some bugs found for initial version:
#1 - There should not be a long delay for loading the part on initial render
#2 - Clicking one of the tabs, and then reload causes it to load blank
#3 - Preview in edit mode simply does not work (shows blank part)

Tested with Firefox

**Comment by hjelmevold** [comment]
#1 I've reduced the script execution time from 250ms down to 50ms, so the part render finishes at around 400ms after page load.
#2 is fixed, and I've also added the ability to display the relevant OS based on the User Agent
#3 I've partially fixed this in the code by adding a placeholder text on the tab row if the part config is empty. However, just like on the Downloads page for enonic.com this part will only update if you reload your whole window, due to how jQuery doesn't work well in Edit mode (race condition?). One way to fully solve this is to write CSS for a static preview without JS and disable the tabs' JS init when shown in Edit mode.

I've deployed the current version of the code to production.
