### ISSUE TITLE
Add "command" macro

### ISSUE THREAD

**Issue by sigdestad** [enonic/site-developer#129]
We need a macro that is able to display a "terminal style" box.

Requirements:

* If a $ sign is written at the beginning of a line, visually make it faded
* Encapsulate in a black terminal window

![Screenshot 2019-03-18 at 13 58 10](https://user-images.githubusercontent.com/482228/54531572-e43a1300-4985-11e9-896a-96d00312ad6c.png)

NB! In this case, the background color is dark grey, macro should only color the terminal

**Comment by hjelmevold** [comment]
I'm going for a single TextArea input in the macro that supports multiple commands using line breaks.

@sigdestad Should the macro add the '$ ' prefix if this is not already provided at the beginning of a line?

And should we use a monospace font which is the browser default for <code> HTML elements, or should we inherit the variable-width site font GT Pressura?

**Comment by hjelmevold** [comment]
Another possibility is to strip away any instances of '$ ' at the beginning of a line and instead always provide these with CSS, so that the user cannot highlight and accidentally copy-paste the prompt sign.

**Comment by sigdestad** [comment]
No, $ must be specified by editor, and only treated specially if line starts with '$ '.
We must use a monospace charset, i.e. courier.

**Comment by sigdestad** [comment]
+1 for the proposed CSS solution to avoid copy mistakes

**Comment by hjelmevold** [comment]
OK, then I'll only use the CSS replacement if the line begins with '$ ', otherwise the text is presented as-is.

**Comment by hjelmevold** [comment]
It turns out that I can't use TextArea and split lines with line break, since the HTML editor replaces line breaks with spaces. And since macros don't support item sets or multiple occurrences of TextLine inputs, I created 9 different TextLine inputs instead. Empty lines are skipped. Result:

<img width="441" alt="Screenshot 2019-03-20 at 15 09 31" src="https://user-images.githubusercontent.com/354917/54690700-3fa10800-4b22-11e9-9a6f-dac80df0ee5a.png">
